# dockerfile-relay.yml - Create Docker image with SMTP multiplicator relay
#
# Distributed under the GNU General Public License version 2 or later, Copyright (c) 2024 Heiko Lübbe
# https://github.com/muhme/joomla-branches-tester

FROM python:3.10-slim

WORKDIR /app

COPY scripts/smtp_multi_relay.py /app/smtp_multi_relay.py

RUN pip install aiosmtpd aiomail

CMD ["python", "smtp_multi_relay.py"]
