#!/bin/bash -e
#
# create - Logger frame for create.sh.
#
# Distributed under the GNU General Public License version 2 or later, Copyright (c) 2024 Heiko Lübbe
# https://github.com/muhme/joomla-branches-tester

log_file="logs/$(date '+%y%m%d%H%M%S').txt"
mkdir -p logs
echo "*** Using '${log_file}' log file"
echo "Starting 'scripts/create.sh $*'" >> "${log_file}"
scripts/create.sh $* 2>&1 | tee -a "${log_file}"
echo "*** Used '${log_file}' log file"
