#!/bin/bash
#
# log - Simple another name for scripts/check.
#
# Distributed under the GNU General Public License version 2 or later
# Copyright (c) 2024 - 2026 Heiko Lübbe and contributors
# https://github.com/muhme/joomla-branches-tester

scripts/check "$@"
